language: node_js

before_install:
- openssl aes-256-cbc -K $encrypted_e6ed02e79e8a_key -iv $encrypted_e6ed02e79e8a_iv
  -in secrets.tar.enc -out secrets.tar -d
- npm install -y gulp-cli

script:
- cd source; gulp dev-init

before_deploy:
- ssh-add wmb-lights-data.key

deploy:
  provider: script
  script: "./deploy.sh"
  on:
    branch: master
